image: alpine:latest

variables:
  REGISTRY_TOKEN: ${CI_JOB_TOKEN}
  REGISTRY_PROJECT_ID: ${CI_PROJECT_ID}
  DTK_VERSION: 1.7.0
  DTK_HOME: /opt/dtk

.shared_runners:
  tags:
    - totally-uat-k8s

stages:
  - test
  - deploy

quality:
  stage: test
  image: composer:latest
  extends:
    - .shared_runners
  before_script:
    - ./build/scripts/install_dtk.sh
  script:
    - ./build/scripts/quality.sh
  rules:
    - if: $CI_COMMIT_BRANCH

test:
  stage: test
  image: composer:latest
  extends:
    - .shared_runners
  before_script:
    - ./build/scripts/install_dtk.sh
  script:
    - ./build/scripts/test.sh
  rules:
    - if: '$CI_COMMIT_BRANCH'

test-coverage:
  stage: test
  image: composer:latest
  extends:
    - .shared_runners
  before_script:
    - ./build/scripts/install_dtk.sh
  script:
    - ./build/scripts/test_coverage.sh
  rules:
    - if: '$CI_COMMIT_BRANCH'

# publish:
#   stage: deploy
#   image: curlimages/curl:latest
#   extends:
#     - .shared_runners
#   rules:
#     - if: $CI_COMMIT_TAG
#       when: always
#   script:
#     - URL="$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$REGISTRY_PROJECT_ID/packages/composer?job_token=$REGISTRY_TOKEN"
#     - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
#     - insecure=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
#     - response=$(curl -s -w "\n%{http_code}" $insecure --data $version $URL)
#     - code=$(echo "$response" | tail -n 1)
#     - body=$(echo "$response" | head -n 1)
#     # Output state information
#     - if [ $code -eq 201 ]; then
#         echo "Package created - Code $code - $body";
#       else
#         echo "Could not create package - Code $code - $body";
#         exit 1;
#       fi
